#!/bin/bash
# Batch 7: the placement ablation that means something -- Mixtral-8x7B, TP=4.
#
# The TP=1 pair (batch 6) came back identical to the picosecond, which is what
# §place predicts: at TP=1 the placement map collapses to the identity. So the
# ablation has to be run where TP>1, and the paper's own old pair came from
# Mixtral-8x7B at dp2 tp4 pp4 ep8 -- 256 GPUs, EP*TP=32, so an EP group spans two
# panels and naive rank order interleaves TP ranks across the boundary.
#
# ONE MAP, BOTH ARMS. experiments/portmaps/mix_dp2tp4pp4ep8.txt, generated by the
# rule-based gen_port_map (16 panels, 28 pairs, <=4 ports of 16 per panel). No
# used-pairs flowlog exists for this configuration, and it does not matter: a
# measured map would only change the comparison if it differed BETWEEN the arms,
# and the same file is handed to both.
#
# WHAT THIS DOES AND DOES NOT ISOLATE. The map is cabled EP-aware. Turning
# placement off therefore measures "naive rank order against cabling laid out for
# EP-aware placement", not "naive rank order against cabling laid out for naive
# rank order". That is the operationally honest question -- you cable a machine
# once and place each job on it -- but it is not the only one, and the sentence
# should say which it answers.
set -uo pipefail
REPO=/storage/scratch1/8/syoon351/repos/panel_scale_glass_flattened_butterfly
cd "$REPO"

SNAP=$REPO/jobsnaps/batch7_$(date +%Y%m%d_%H%M%S)
mkdir -p "$SNAP"; cp scripts/rung.sh "$SNAP/rung.sh"; chmod +x "$SNAP/rung.sh"
RUN="$SNAP/rung.sh"

LINK_RATE_FIXED=""
grep -q "8ULL \* 1000000000000ULL" "$REPO/src/clos/queue.h" 2>/dev/null &&
  [ "$REPO/src/clos/datacenter/htsim_tcp_glassfb_pm" -nt "$REPO/src/clos/queue.o" ] &&
  LINK_RATE_FIXED=yes
export LINK_RATE_FIXED
export HTSIM_BINARY_SHA="$(git rev-parse --short HEAD)"
[ "$LINK_RATE_FIXED" = yes ] || { echo "REFUSING: binary lacks the link-rate fix" >&2; exit 1; }
echo "link_rate_fixed=$LINK_RATE_FIXED  binary_sha=$HTSIM_BINARY_SHA"

MAP=mix_dp2tp4pp4ep8.txt
[ -f "$REPO/experiments/portmaps/$MAP" ] || { echo "FATAL: $MAP not generated" >&2; exit 1; }

OUTD=$REPO/experiments/results/paper/rungs
guard () {
  [ -e "$OUTD/$1.csv" ] && { echo "REFUSING $1: output exists" >&2; return 1; }
  squeue -u "$USER" -h -o '%j' 2>/dev/null | grep -qx "b7_$1" && { echo "REFUSING $1: already queued" >&2; return 1; }
  return 0
}

N=0
sub () { # mem time tag args...
  local mem=$1 tm=$2 tag=$3; shift 3
  if [ -n "${ONLY:-}" ]; then case " $ONLY " in *" $tag "*) ;; *) return 0 ;; esac; fi
  guard "$tag" || return 0
  if [ "${DRY_RUN:-0}" = 1 ]; then
    N=$((N+1)); printf "  WOULD SUBMIT  %-16s mem=%-5s t=%-9s  %s\n" "$tag" "$mem" "$tm" "$*"; return 0
  fi
  local id
  id=$(sbatch --parsable --export=ALL -J "b7_$tag" -A gts-syu334-ece -p cpu-medium \
       -q inferno -N 1 -n 1 -c 4 --mem="$mem" -t "$tm" \
       -o "$REPO/slurm_b7_${tag}_%j.out" -e "$REPO/slurm_b7_${tag}_%j.err" \
       --wrap "bash $RUN $*")
  N=$((N+1)); printf "  %-22s %s\n" "$tag" "$id"
}

MIX=mixtral8x7B_paper_dp2tp4pp4_ep8top2_L4_seq1024_mb8_H100.fbuf

# 2x/4x/8x of the 400 GB/s port BDP (266.7 pkt at MTU 1500, RTT 4x250 ns), the
# same rungs the EP=32 walk uses on the same port rate.
echo "### placement ON"
export RUNG_EP_PLACE=1
for q in 533 1066 2133; do
  sub 20G 8:00:00 "mixon_q$q" glass 8 256 "$MIX" wm_ep32.txt "$MAP" "$q" 8 "mixon_q$q"
done

echo "### placement OFF (naive rank order)"
export RUNG_EP_PLACE=0
for q in 533 1066 2133; do
  sub 20G 8:00:00 "mixoff_q$q" glass 8 256 "$MIX" wm_ep32.txt "$MAP" "$q" 8 "mixoff_q$q"
done
unset RUNG_EP_PLACE

echo
echo "submitted/listed $N job(s)"
